# Generated by Django 3.2.19 on 2023-12-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0005_auto_20231208_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
