# Generated by Django 3.2.19 on 2023-12-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0006_alter_salesinvoice_subtotal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sale_transaction',
            new_name='saleorder_transaction',
        ),
    ]
