# Generated by Django 3.2.19 on 2023-12-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0009_remove_salesorder_partyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='partyname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
