# Generated by Django 3.2.19 on 2023-12-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0010_salesorder_partyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_item',
            name='taxamount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
