# Generated by Django 3.2.19 on 2023-12-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0011_sales_item_taxamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
